package certdeck

import (
	"fmt"
	"strings"
)

// BuildUdmLeEnvSnippet returns a starter udm-le.env fragment aligned with
// https://github.com/kchristensen/udm-le — paste on the UDM under /data/udm-le/ after cloning the repo.
func BuildUdmLeEnvSnippet(cfg AppConfig) string {
	email := strings.TrimSpace(cfg.CertEmail)
	if email == "" {
		email = "your@email.com"
	}
	hosts := strings.TrimSpace(cfg.CertHosts)
	if hosts == "" {
		hosts = "unifi.example.com"
	}
	days := cfg.CertDaysBeforeRenewal
	if days <= 0 {
		days = 30
	}
	prov := strings.ToLower(strings.TrimSpace(cfg.DNSProvider))
	if prov == "" {
		prov = "cloudflare"
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by UniFi Cert Smash Deck (udm-le helper). Review before use.\n")
	fmt.Fprintf(&b, "# Upstream template: https://github.com/kchristensen/udm-le/blob/master/udm-le.env\n\n")
	fmt.Fprintf(&b, "CERT_EMAIL=%q\n", email)
	fmt.Fprintf(&b, "CERT_HOSTS=%q\n", hosts)
	fmt.Fprintf(&b, "CERT_DAYS_BEFORE_RENEWAL=%q\n", fmt.Sprintf("%d", days))
	fmt.Fprintf(&b, "ENABLE_CAPTIVE=\"no\"\n")
	fmt.Fprintf(&b, "NO_BUNDLE=\"no\"\n")
	fmt.Fprintf(&b, "ENABLE_EUS_CERTS=\"yes\"\n")
	fmt.Fprintf(&b, "KEY_TYPE=\"RSA2048\"\n")
	fmt.Fprintf(&b, "ENABLE_RADIUS=\"no\"\n")
	fmt.Fprintf(&b, "LEGO_DISABLE_CNAME_SUPPORT=true\n")
	fmt.Fprintf(&b, "DNS_RESOLVER=\"127.0.0.1:53\"\n\n")

	appendProviderBlock(&b, prov)

	fmt.Fprintf(&b, "\nEXTRA_ARGS=\"\"\n")
	fmt.Fprintf(&b, "DNS_RESOLVERS=\"\"\n")
	fmt.Fprintf(&b, "UDM_LE_PATH=\"/data/udm-le\"\n")
	return b.String()
}

// BuildUdmLeEnvWithToken calls BuildUdmLeEnvSnippet and replaces provider-specific token
// placeholders with the real token value.
func BuildUdmLeEnvWithToken(cfg AppConfig, token string) string {
	snippet := BuildUdmLeEnvSnippet(cfg)
	token = strings.TrimSpace(token)
	if token == "" {
		return snippet
	}

	prov := strings.ToLower(strings.TrimSpace(cfg.DNSProvider))
	switch prov {
	case "cloudflare":
		snippet = strings.ReplaceAll(snippet,
			`CLOUDFLARE_DNS_API_TOKEN="YOUR_CLOUDFLARE_API_TOKEN"`,
			fmt.Sprintf(`CLOUDFLARE_DNS_API_TOKEN=%q`, token))
	case "digitalocean":
		snippet = strings.ReplaceAll(snippet, "DO_AUTH_TOKEN=", "DO_AUTH_TOKEN="+token)
	case "duckdns":
		snippet = strings.ReplaceAll(snippet,
			`DUCKDNS_TOKEN="AUTH_TOKEN"`,
			fmt.Sprintf(`DUCKDNS_TOKEN=%q`, token))
	case "route53":
		// Route53 uses key+secret; treat token as secret access key placeholder.
		snippet = strings.ReplaceAll(snippet,
			`AWS_SECRET_ACCESS_KEY=""`,
			fmt.Sprintf(`AWS_SECRET_ACCESS_KEY=%q`, token))
	case "linode":
		snippet = strings.ReplaceAll(snippet,
			`LINODE_TOKEN=""`,
			fmt.Sprintf(`LINODE_TOKEN=%q`, token))
	}
	return snippet
}

func appendProviderBlock(b *strings.Builder, prov string) {
	switch prov {
	case "cloudflare":
		fmt.Fprintf(b, "DNS_PROVIDER=\"cloudflare\"\n")
		fmt.Fprintf(b, "# Create an API token with DNS edit on your zone; place on the UDM only:\n")
		fmt.Fprintf(b, "CLOUDFLARE_DNS_API_TOKEN=\"YOUR_CLOUDFLARE_API_TOKEN\"\n")
	case "route53":
		fmt.Fprintf(b, "DNS_PROVIDER=\"route53\"\n")
		fmt.Fprintf(b, "AWS_ACCESS_KEY_ID=\"\"\n")
		fmt.Fprintf(b, "AWS_SECRET_ACCESS_KEY=\"\"\n")
		fmt.Fprintf(b, "AWS_REGION=\"\"\n")
		fmt.Fprintf(b, "AWS_HOSTED_ZONE_ID=\"\"\n")
	case "digitalocean":
		fmt.Fprintf(b, "DNS_PROVIDER=\"digitalocean\"\n")
		fmt.Fprintf(b, "# Note: quoting DO_AUTH_TOKEN in udm-le.env can cause issues — see udm-le README.\n")
		fmt.Fprintf(b, "DO_AUTH_TOKEN=\n")
	case "duckdns":
		fmt.Fprintf(b, "DNS_PROVIDER=\"duckdns\"\n")
		fmt.Fprintf(b, "DUCKDNS_TOKEN=\"AUTH_TOKEN\"\n")
	case "azure":
		fmt.Fprintf(b, "DNS_PROVIDER=\"azure\"\n")
		fmt.Fprintf(b, "AZURE_CLIENT_ID=\"\"\n")
		fmt.Fprintf(b, "AZURE_CLIENT_SECRET_FILE=\"/data/udm-le/.secrets/client-secret.txt\"\n")
		fmt.Fprintf(b, "AZURE_ENVIRONMENT=\"public\"\n")
		fmt.Fprintf(b, "AZURE_RESOURCE_GROUP=\"udm-le\"\n")
		fmt.Fprintf(b, "AZURE_SUBSCRIPTION_ID=\"\"\n")
		fmt.Fprintf(b, "AZURE_TENANT_ID=\"\"\n")
	case "gcloud":
		fmt.Fprintf(b, "DNS_PROVIDER=\"gcloud\"\n")
		fmt.Fprintf(b, "GCE_SERVICE_ACCOUNT_FILE=\"/data/udm-le/.secrets/sa.json\"\n")
		fmt.Fprintf(b, "GCE_PROPAGATION_TIMEOUT=\"3600\"\n")
	case "linode":
		fmt.Fprintf(b, "DNS_PROVIDER=\"linode\"\n")
		fmt.Fprintf(b, "LINODE_TOKEN=\"\"\n")
		fmt.Fprintf(b, "LINODE_PROPAGATION_TIMEOUT=\"120\"\n")
	default:
		fmt.Fprintf(b, "# DNS_PROVIDER: set manually (see udm-le README / lego DNS providers).\n")
		fmt.Fprintf(b, "# Example: DNS_PROVIDER=\"cloudflare\"\n")
	}
}
